version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '09:00'
      # Use Indian Time (UTC +05:30)
      timezone: "Asia/Kolkata"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: golang.org/x/sys
        update-types:
          - version-update:semver-patch

